"""Autodetection of agent and verify command (A2)."""

from __future__ import annotations

import shutil

from looptight import detect


def test_detect_verify_python_pyproject(tmp_path):
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_uv_lock_prefers_uv_run_pytest(tmp_path):
    # A uv-managed project has both pyproject.toml and uv.lock. In a fresh
    # uv-only env pytest is not on PATH, so detect_verify must return
    # "uv run pytest -q" rather than "pytest -q".
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "uv.lock").write_text("version = 1\n")
    assert detect.detect_verify(tmp_path) == "uv run pytest -q"


def test_detect_verify_pdm_lock_prefers_pdm_run_pytest(tmp_path):
    # A pdm-managed project has both pyproject.toml and pdm.lock. In a fresh
    # pdm-only env pytest is not on PATH, so detect_verify must return
    # "pdm run pytest -q" rather than "pytest -q".
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "pdm.lock").write_text("# generated by pdm\n")
    assert detect.detect_verify(tmp_path) == "pdm run pytest -q"


def test_detect_verify_poetry_lock_prefers_poetry_run_pytest(tmp_path):
    # A poetry-managed project has both pyproject.toml and poetry.lock. In a fresh
    # poetry-only env pytest is not on PATH, so detect_verify must return
    # "poetry run pytest -q" rather than "pytest -q".
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "poetry.lock").write_text("# generated by poetry\n")
    assert detect.detect_verify(tmp_path) == "poetry run pytest -q"


def test_detect_verify_uv_wins_over_poetry(tmp_path):
    # When pyproject.toml, uv.lock, and poetry.lock all coexist, uv.lock must win
    # because detect.py:95 checks it first. A regression swapping those two guards
    # would silently return "poetry run pytest -q" with no existing test failing.
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "uv.lock").write_text("version = 1\n")
    (tmp_path / "poetry.lock").write_text("# generated by poetry\n")
    assert detect.detect_verify(tmp_path) == "uv run pytest -q"


def test_detect_verify_poetry_wins_over_pdm(tmp_path):
    # detect.py:97 — when pyproject.toml, poetry.lock, and pdm.lock all coexist,
    # poetry.lock must win because line 97 checks it before line 99. A regression
    # swapping those two guards would silently return "pdm run pytest -q" with no
    # existing test failing.
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "poetry.lock").write_text("# generated by poetry\n")
    (tmp_path / "pdm.lock").write_text("# generated by pdm\n")
    assert detect.detect_verify(tmp_path) == "poetry run pytest -q"


def test_detect_verify_uv_wins_over_pdm(tmp_path):
    # detect.py:102 checks uv.lock before line 106 checks pdm.lock. A mutation
    # swapping those two guards would silently return "pdm run pytest -q" with no
    # existing test failing.
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "uv.lock").write_text("version = 1\n")
    (tmp_path / "pdm.lock").write_text("# generated by pdm\n")
    assert detect.detect_verify(tmp_path) == "uv run pytest -q"


def test_detect_verify_pytest_from_test_files_without_config(tmp_path):
    # A plain pytest project (test files, no pyproject/setup.cfg/etc.) should be detected as
    # pytest rather than reported as "no test command detected".
    (tmp_path / "test_calc.py").write_text("def test_x():\n    assert True\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_pytest_from_tests_dir(tmp_path):
    tests = tmp_path / "tests"
    tests.mkdir()
    (tests / "conftest.py").write_text("")
    (tests / "test_thing.py").write_text("def test_x():\n    assert True\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_pytest_from_test_singular_dir(tmp_path):
    test_dir = tmp_path / "test"
    test_dir.mkdir()
    (test_dir / "test_thing.py").write_text("def test_x():\n    assert True\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_pytest_from_suffix_named_test_file(tmp_path):
    (tmp_path / "calc_test.py").write_text("def test_add():\n    assert 1 + 1 == 2\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_pytest_from_conftest_only(tmp_path):
    # detect.py:117-118: conftest.py alone (no test_*.py files) must be enough to detect pytest.
    # The branch was only exercised with test_thing.py present, so this pins it directly.
    (tmp_path / "conftest.py").write_text("")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_pytest_from_conftest_only_in_test_singular_dir(tmp_path):
    # detect.py:121 — the third loop iteration (base / "test") shares the conftest.py check
    # with the root and tests/ iterations. Without a direct test, a mutation narrowing the
    # loop to two directories would break conftest-only detection in test/ (singular) silently.
    test_dir = tmp_path / "test"
    test_dir.mkdir()
    (test_dir / "conftest.py").write_text("")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_none_for_repo_without_tests_or_config(tmp_path):
    (tmp_path / "main.py").write_text("print('hi')\n")  # code, but no tests and no config
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_go(tmp_path):
    (tmp_path / "go.mod").write_text("module x\n")
    assert detect.detect_verify(tmp_path) == "go test ./..."


def test_detect_verify_deno_json(tmp_path):
    (tmp_path / "deno.json").write_text('{"tasks": {}}\n')
    assert detect.detect_verify(tmp_path) == "deno test"


def test_detect_verify_deno_jsonc(tmp_path):
    (tmp_path / "deno.jsonc").write_text("{}\n")
    assert detect.detect_verify(tmp_path) == "deno test"


def test_detect_verify_gradle_prefers_wrapper(tmp_path):
    # JVM projects (Gradle/Maven) are a top ecosystem; detect must not fall back to
    # the pytest default for them. The committed wrapper is preferred when present
    # (version-pinned, needs no global install), else the bare tool on PATH.
    (tmp_path / "build.gradle").write_text("plugins { id 'java' }\n")
    assert detect.detect_verify(tmp_path) == "gradle test"
    (tmp_path / "gradlew").write_text("#!/bin/sh\n")
    assert detect.detect_verify(tmp_path) == "./gradlew test"


def test_detect_verify_gradle_kotlin_dsl(tmp_path):
    (tmp_path / "build.gradle.kts").write_text('plugins { kotlin("jvm") }\n')
    assert detect.detect_verify(tmp_path) == "gradle test"


def test_detect_verify_maven_prefers_wrapper(tmp_path):
    (tmp_path / "pom.xml").write_text("<project></project>\n")
    assert detect.detect_verify(tmp_path) == "mvn test"
    (tmp_path / "mvnw").write_text("#!/bin/sh\n")
    assert detect.detect_verify(tmp_path) == "./mvnw test"


def test_detect_verify_elixir(tmp_path):
    # mix is Elixir's single, unambiguous test runner.
    (tmp_path / "mix.exs").write_text("defmodule X.MixProject do\nend\n")
    assert detect.detect_verify(tmp_path) == "mix test"


def test_detect_verify_swift(tmp_path):
    # SwiftPM's standard test command for a Package.swift manifest.
    (tmp_path / "Package.swift").write_text("// swift-tools-version:5.9\n")
    assert detect.detect_verify(tmp_path) == "swift test"


def test_detect_verify_dotnet(tmp_path):
    # .NET is a dominant ecosystem; a solution or project file maps to `dotnet test`
    # (the unambiguous standard) rather than the pytest fallback. Project files are
    # arbitrarily named, so detection globs for the well-known extensions.
    (tmp_path / "MyApp.sln").write_text("Microsoft Visual Studio Solution File\n")
    assert detect.detect_verify(tmp_path) == "dotnet test"


def test_detect_verify_dotnet_csproj(tmp_path):
    # detect.py:98 — .csproj glob matches inside the project root.
    (tmp_path / "MyLib.csproj").write_text("<Project></Project>\n")
    assert detect.detect_verify(tmp_path) == "dotnet test"


def test_detect_verify_dotnet_csproj_only(tmp_path):
    (tmp_path / "MyLib.csproj").write_text("<Project></Project>\n")
    assert detect.detect_verify(tmp_path) == "dotnet test"


def test_detect_verify_dotnet_fsproj_only(tmp_path):
    (tmp_path / "MyLib.fsproj").write_text("<Project></Project>\n")
    assert detect.detect_verify(tmp_path) == "dotnet test"


def test_detect_verify_dotnet_vbproj_only(tmp_path):
    (tmp_path / "MyApp.vbproj").write_text("<Project></Project>\n")
    assert detect.detect_verify(tmp_path) == "dotnet test"


def test_detect_verify_makefile_check_target(tmp_path):
    # `make check` (GNU/autotools, and a common "run all checks" target) is detected
    # as a fallback after `make test`; near-miss target names do not match.
    (tmp_path / "Makefile").write_text("check:\n\tpytest\n")
    assert detect.detect_verify(tmp_path) == "make check"


def test_detect_verify_makefile_prefers_test_over_check(tmp_path):
    (tmp_path / "Makefile").write_text("check: test\n\ntest:\n\tpytest\n")
    assert detect.detect_verify(tmp_path) == "make test"


def test_detect_verify_makefile_check_near_misses_dont_match(tmp_path):
    (tmp_path / "Makefile").write_text("checkfmt:\n\truff format\ncheck-lint:\n\truff check\n")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_justfile_test_recipe(tmp_path):
    (tmp_path / "justfile").write_text("test:\n    pytest\n")
    assert detect.detect_verify(tmp_path) == "just test"


def test_detect_verify_justfile_check_recipe_capitalized(tmp_path):
    (tmp_path / "Justfile").write_text("check:\n    pytest\n")
    assert detect.detect_verify(tmp_path) == "just check"


def test_detect_verify_justfile_prefers_test_over_check(tmp_path):
    (tmp_path / "justfile").write_text("check: test\n\ntest:\n    pytest\n")
    assert detect.detect_verify(tmp_path) == "just test"


def test_detect_verify_justfile_no_test_recipe(tmp_path):
    (tmp_path / "justfile").write_text("build:\n    echo hi\n")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_npm_only_with_test_script(tmp_path):
    (tmp_path / "package.json").write_text('{"scripts": {"test": "vitest"}}')
    assert detect.detect_verify(tmp_path) == "npm test"


def test_detect_verify_npm_without_test_script_falls_through(tmp_path):
    (tmp_path / "package.json").write_text('{"scripts": {"build": "tsc"}}')
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_falls_through_npm_to_uv_when_no_test_script(tmp_path):
    # detect.py:58-81: when package.json has no test script, the npm branch
    # falls through to the uv.lock branch and returns "uv run pytest -q".
    (tmp_path / "package.json").write_text('{"scripts": {"build": "tsc"}}')
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    (tmp_path / "uv.lock").write_text("version = 1\n")
    assert detect.detect_verify(tmp_path) == "uv run pytest -q"


def test_detect_verify_npm_placeholder_test_script_falls_through(tmp_path):
    # `npm init` writes a placeholder test that always exits 1. Claiming `npm
    # test` for it would make every verify fail and stall the loop before the
    # user has written a single test, so it must not count as a real gate.
    (tmp_path / "package.json").write_text(
        '{"scripts": {"test": "echo \\"Error: no test specified\\" && exit 1"}}'
    )
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_npm_malformed_json_falls_through(tmp_path):
    (tmp_path / "package.json").write_text("{ not valid json }")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_npm_non_object_scripts_falls_through(tmp_path):
    (tmp_path / "package.json").write_text('{"scripts": null}')
    (tmp_path / "pyproject.toml").write_text("[project]\nname='x'\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_npm_non_dict_manifest_falls_through(tmp_path):
    (tmp_path / "package.json").write_text("[]")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_npm_non_dict_scripts_falls_through(tmp_path):
    # detect.py:81 — `if not isinstance(scripts, dict): scripts = {}` fires when the
    # "scripts" field is an array or other non-object JSON value; should fall through to None.
    (tmp_path / "package.json").write_text('{"scripts": [1, 2, 3]}')
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_npm_non_string_test_script_falls_through(tmp_path):
    (tmp_path / "package.json").write_text('{"scripts": {"test": 42}}')
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_non_utf8_package_json_falls_through(tmp_path):
    # A non-UTF-8 package.json raises UnicodeDecodeError (a ValueError) at
    # detect.py:64; the except (ValueError, OSError) at line 74 must catch it
    # and fall through to None rather than crashing detect_verify.
    (tmp_path / "package.json").write_bytes(b'{"scripts": {"test": "\xff\xfe broken"}}')
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_oserror_on_package_json_falls_through(tmp_path):
    # detect.py:74's OSError arm: a directory named package.json raises
    # IsADirectoryError (an OSError) at read_text; the except must catch it and
    # fall through to None rather than crashing detect_verify.
    (tmp_path / "package.json").mkdir()
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_setup_cfg(tmp_path):
    (tmp_path / "setup.cfg").write_text("[metadata]\nname = x\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_pytest_ini(tmp_path):
    (tmp_path / "pytest.ini").write_text("[pytest]\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_tox_ini(tmp_path):
    (tmp_path / "tox.ini").write_text("[tox]\n")
    assert detect.detect_verify(tmp_path) == "pytest -q"


def test_detect_verify_cargo(tmp_path):
    (tmp_path / "Cargo.toml").write_text("[package]\nname = 'x'\n")
    assert detect.detect_verify(tmp_path) == "cargo test"


def test_detect_verify_makefile(tmp_path):
    (tmp_path / "Makefile").write_text("test:\n\tpytest\n")
    assert detect.detect_verify(tmp_path) == "make test"


def test_detect_verify_non_utf8_makefile_falls_through(tmp_path):
    # A non-UTF-8 Makefile must not crash detection; it falls through to None,
    # matching how the package.json branch tolerates an unreadable file.
    (tmp_path / "Makefile").write_bytes(b"test:\n\t\xff\xfe not utf-8\n")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_non_utf8_justfile_falls_through(tmp_path):
    # A non-UTF-8 justfile exercises the same _recipe_runner exception branch as
    # the Makefile test above, but via the justfile detection path.
    (tmp_path / "justfile").write_bytes(b"test:\n\t\xff\xfe not utf-8\n")
    assert detect.detect_verify(tmp_path) is None


def test_recipe_runner_oserror_falls_through(tmp_path):
    # detect.py:163-167 — the OSError arm of `except (OSError, ValueError)` in
    # `_recipe_runner`: both existing makefile tests trigger UnicodeDecodeError (a
    # ValueError subclass); a plain OSError on a file that passes `.is_file()` is
    # never exercised. A directory named "Makefile" raises IsADirectoryError
    # (an OSError subclass) at read_text, so detection must fall through to None.
    (tmp_path / "Makefile").mkdir()
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_makefile_ignores_test_assignment(tmp_path):
    # `test:=...` / `test::=...` are Make variable assignments, not targets, so
    # they must not be mistaken for a `make test` rule.
    (tmp_path / "Makefile").write_text("test:=pytest\n\nbuild:\n\tgcc x.c\n")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_makefile_target_with_prereqs(tmp_path):
    # A real target with prerequisites is still detected.
    (tmp_path / "Makefile").write_text("test: build\n\tpytest\n")
    assert detect.detect_verify(tmp_path) == "make test"


def test_detect_verify_makefile_genuine_target_detected(tmp_path):
    # A real `test:` target is recognized even when a commented line precedes it.
    (tmp_path / "Makefile").write_text("# test: run the suite manually\ntest:\n\tpytest\n")
    assert detect.detect_verify(tmp_path) == "make test"


def test_detect_verify_makefile_ignores_commented_test(tmp_path):
    # A commented `# test:` line (even indented) must not be read as a target.
    (tmp_path / "Makefile").write_text("# test: explains the workflow\n  # test: indented note\nbuild:\n\tgcc x.c\n")
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_hidden_dotfile_justfile(tmp_path):
    # detect.py:108 includes ".justfile" in the loop but no test ever exercised it.
    (tmp_path / ".justfile").write_text("test:\n    pytest\n")
    assert detect.detect_verify(tmp_path) == "just test"


def test_detect_verify_none(tmp_path):
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_ruby_gemfile_returns_none(tmp_path):
    # Ruby (Gemfile) is deliberately not supported; no test runner is inferred.
    (tmp_path / "Gemfile").write_text('source "https://rubygems.org"\ngem "rspec"\n')
    assert detect.detect_verify(tmp_path) is None


def test_detect_verify_php_composer_returns_none(tmp_path):
    # PHP (composer.json) is deliberately not supported; no test runner is inferred.
    (tmp_path / "composer.json").write_text('{"require": {"php": ">=8.0"}}\n')
    assert detect.detect_verify(tmp_path) is None


def test_detect_agent_prefers_known_order(monkeypatch):
    monkeypatch.setattr(shutil, "which", lambda name: "/usr/bin/codex" if name == "codex" else None)
    assert detect.detect_agent() == "codex"


def test_detect_agent_honors_preferred(monkeypatch):
    monkeypatch.setattr(shutil, "which", lambda name: f"/usr/bin/{name}")
    assert detect.detect_agent("opencode") == "opencode"


def test_detect_agent_none_when_absent(monkeypatch):
    monkeypatch.setattr(shutil, "which", lambda name: None)
    assert detect.detect_agent() is None


def test_detect_agent_preferred_not_on_path_returns_none_not_fallback(monkeypatch):
    # When a preferred agent is given but not on PATH, the function must return
    # None rather than falling through to pick a different available agent.
    monkeypatch.setattr(shutil, "which", lambda name: "/usr/bin/claude" if name == "claude" else None)
    assert detect.detect_agent("codex") is None


def test_detect_agent_returns_first_known_agent_on_path(monkeypatch):
    # detect.py:33-35 — when preferred is None and "claude" (first in KNOWN_AGENTS)
    # is on PATH, the loop returns it immediately without checking further entries.
    monkeypatch.setattr(shutil, "which", lambda name: "/usr/bin/claude" if name == "claude" else None)
    assert detect.detect_agent() == "claude"


def test_detect_verify_bun_lockb_returns_bun_test(tmp_path):
    # A directory with only bun.lockb has no package.json test script, but Bun
    # has its own built-in test runner; detect_verify must return "bun test".
    (tmp_path / "bun.lockb").write_bytes(b"")  # binary lock file
    assert detect.detect_verify(tmp_path) == "bun test"


def test_detect_verify_bun_wins_over_npm_test_script(tmp_path):
    # bun.lockb must be checked before package.json so a Bun project that also
    # carries a package.json with a real test script still returns "bun test",
    # not "npm test" (npm may not be installed in a Bun-only environment).
    (tmp_path / "bun.lockb").write_bytes(b"")
    (tmp_path / "package.json").write_text('{"scripts": {"test": "bun test"}}')
    assert detect.detect_verify(tmp_path) == "bun test"


def test_detect_verify_pnpm_lock_returns_pnpm_test(tmp_path):
    # pnpm-lock.yaml indicates a pnpm project; detect_verify must return "pnpm test"
    # even without a package.json (pnpm may not have npm installed).
    (tmp_path / "pnpm-lock.yaml").write_text("lockfileVersion: '6.0'\n")
    assert detect.detect_verify(tmp_path) == "pnpm test"


def test_detect_verify_pnpm_wins_over_npm_test_script(tmp_path):
    # pnpm-lock.yaml must be checked before package.json so a pnpm project that
    # also carries a package.json with a real test script returns "pnpm test",
    # not "npm test" (npm may not be installed in a pnpm-only environment).
    (tmp_path / "pnpm-lock.yaml").write_text("lockfileVersion: '6.0'\n")
    (tmp_path / "package.json").write_text('{"scripts": {"test": "vitest"}}')
    assert detect.detect_verify(tmp_path) == "pnpm test"


def test_detect_verify_yarn_lock_returns_yarn_test(tmp_path):
    # yarn.lock indicates a Yarn project; detect_verify must return "yarn test"
    # even without a package.json (Yarn may not have npm installed).
    (tmp_path / "yarn.lock").write_text("# yarn lockfile v1\n")
    assert detect.detect_verify(tmp_path) == "yarn test"


def test_detect_verify_yarn_wins_over_npm_test_script(tmp_path):
    # yarn.lock must be checked before package.json so a Yarn project that also
    # carries a package.json with a real test script returns "yarn test",
    # not "npm test".
    (tmp_path / "yarn.lock").write_text("# yarn lockfile v1\n")
    (tmp_path / "package.json").write_text('{"scripts": {"test": "jest"}}')
    assert detect.detect_verify(tmp_path) == "yarn test"


def test_detect_verify_pnpm_wins_over_yarn(tmp_path):
    # When both pnpm-lock.yaml and yarn.lock coexist, pnpm-lock.yaml must win
    # because detect.py:68 checks it first. A regression that swaps those two
    # guards would silently return "yarn test" with no existing test failing.
    (tmp_path / "pnpm-lock.yaml").write_text("lockfileVersion: '6.0'\n")
    (tmp_path / "yarn.lock").write_text("# yarn lockfile v1\n")
    assert detect.detect_verify(tmp_path) == "pnpm test"


def test_detect_verify_bun_wins_over_pnpm_and_yarn(tmp_path):
    # When bun.lockb, pnpm-lock.yaml, and yarn.lock all exist, bun.lockb must
    # win because detect.py:59 checks it first. A regression that reorders or
    # removes a guard would silently change the returned command.
    (tmp_path / "bun.lockb").write_bytes(b"")
    (tmp_path / "pnpm-lock.yaml").write_text("lockfileVersion: '6.0'\n")
    (tmp_path / "yarn.lock").write_text("# yarn lockfile v1\n")
    assert detect.detect_verify(tmp_path) == "bun test"


def test_detect_verify_crystal(tmp_path):
    # Crystal's shard.yml is a distinctive marker; crystal spec is the single
    # unambiguous test runner, analogous to Elixir (mix.exs) and Swift (Package.swift).
    (tmp_path / "shard.yml").write_text('name: myapp\nversion: 0.1.0\n')
    assert detect.detect_verify(tmp_path) == "crystal spec"


def test_detect_verify_pipenv_lock_returns_pipenv_run_pytest(tmp_path):
    # Pipenv projects carry a Pipfile.lock; pipenv run pytest -q is the unambiguous
    # test runner for them, matching the pattern for uv.lock, poetry.lock, pdm.lock.
    (tmp_path / "Pipfile.lock").write_text('{"default": {}, "_meta": {}}\n')
    assert detect.detect_verify(tmp_path) == "pipenv run pytest -q"


def test_detect_verify_pipenv_wins_over_pyproject(tmp_path):
    # Pipfile.lock must be checked before pyproject.toml so a project that has both
    # (e.g., a pyproject.toml for metadata + Pipenv for the environment) prefers pipenv.
    (tmp_path / "Pipfile.lock").write_text('{"default": {}, "_meta": {}}\n')
    (tmp_path / "pyproject.toml").write_text('[tool.pytest.ini_options]\n')
    assert detect.detect_verify(tmp_path) == "pipenv run pytest -q"
